### ISSUE TITLE
Multiple levels, winning and losing

### ISSUE THREAD

**Issue by 8uurg** [lkroesen/BubbleBobble#12]
Multiple levels: On winning a level, the player goes on to the next level, or, if there is no next level, wins the game.

Winning: When all enemies are dead, the player wins a level.
Losing: When the player gets hit by an enemy, the player loses.

**Comment by Tarovk** [comment]
Winning is half implemented, losing is still not possible. 
Unfortunately we didn't have enough time to fix this entirely this week.
This should be incorporated in to next weeks sprint.

**Comment by lkroesen** [comment]
Partially fixed in PR #20, Multiple levels, Winning and losing contained in PR #35
