### ISSUE TITLE
Bubble can be spammed

### ISSUE THREAD

**Issue by LarsStegman** [lkroesen/BubbleBobble#21]
You can spam an infinite amount of bubbles, which makes it very easy to beat a level. It also freezes the game when too many bubbles are created.

**Comment by 8uurg** [comment]
I am unable to reproduce the game freeze when too many bubbles are created.
(I can spam the bubbles at max amount for a good amount of time)

I do however, get a ConcurrentModificationException at the forEach in the JBubbleBobbleKeylistener.

**Comment by LarsStegman** [comment]
The game freezing happens, when the logger prints to the console.

**Comment by 8uurg** [comment]
Isn't the logger printing threaded? @lkroesen ?

**Comment by lkroesen** [comment]
I haven't had this issue at all while testing and playing?

**Comment by LarsStegman** [comment]
It seems to happen when IntelliJ is in another virtual desktop and off screen. The game freezes until IntelliJ can display the console again. I think it's a problem with IntelliJ which we can do nothing about. I'll close the issue.

**Comment by Tarovk** [comment]
I think this will be resolved as of PR #23
