### ISSUE TITLE
Bubbles don't dissapear on collision

### ISSUE THREAD

**Issue by Tarovk** [lkroesen/BubbleBobble#29]
Apparently bubbles don't dissapear in semi-rare cases.

![image](https://cloud.githubusercontent.com/assets/12841723/9971351/7e75cba4-5e5b-11e5-9a7e-a3274e705dc2.png)

**Comment by lkroesen** [comment]
Fixed as of: https://github.com/lkroesen/BubbleBobble/pull/31
