### ISSUE TITLE
Travis Launchertest bug

### ISSUE THREAD

**Issue by lkroesen** [lkroesen/BubbleBobble#83]
Launchertest won't run on travis, further investigation required.

**Comment by 8uurg** [comment]
This only affects the keybindings branch. Maybe nice to keep in mind.

**Comment by lkroesen** [comment]
Yes, that is indeed something to keep in mind, however, there is a fix, but this fix does not work on Travis because we do not have file write permissions maybe? I'm not sure, but it has been fixed locally for maven --test.
